name: Playwright Tests

on:
  # Daily run at 08:00 AM IST (02:30 UTC)
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      SUITE_NAME: PlaywrightGreenKartTest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          echo "Running Suite: $SUITE_NAME"
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.SUITE_NAME }}-Report
          path: playwright-report/
          retention-days: 30
